// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SpellChecker
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("spellPass")]
        public bool SpellPass { get; set; }

        [JsonProperty("mispellingsFound")]
        public long MispellingsFound { get; set; }

        [JsonProperty("corrections")]
        public Correction[] Corrections { get; set; }
    }

    public partial class Correction
    {
        [JsonProperty("word")]
        public string Word { get; set; }

        [JsonProperty("suggestions")]
        public string[] Suggestions { get; set; }
    }
}
